version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  database:
    image: postgres:14.2-alpine
    container_name: postgres
    networks:
      - app-tier
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: kafkaPracticeDb
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - app-tier
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-tier
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  application:
    build: .
    container_name: kafka-practice-app
    networks:
      - app-tier
    ports:
      - 7000:7000
      - 7001:7001
    expose:
      - 7000
      - 7001
    environment:
      JDBC_DATASOURCE_URL: jdbc:postgresql://database:5432/kafkaPracticeDb
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - database
      - zookeeper
      - kafka